export const ProductLitByCategory = async (req, res) => {
  try {
    return res.json({ status: "success" });
  } catch (error) {
    return res.json({ status: "fail", message: error.toString() });
  }
};
export const ProductLitByRemark = async (req, res) => {
  try {
    return res.json({ status: "success" });
  } catch (error) {
    return res.json({ status: "fail", message: error.toString() });
  }
};

export const ProductLitByBrand = async (req, res) => {
  try {
    return res.json({ status: "success" });
  } catch (error) {
    return res.json({ status: "fail", message: error.toString() });
  }
};

export const ProductLitBySlider = async (req, res) => {
  try {
    return res.json({ status: "success" });
  } catch (error) {
    return res.json({ status: "fail", message: error.toString() });
  }
};

export const ProductDetailsID = async (req, res) => {
  try {
    return res.json({ status: "success" });
  } catch (error) {
    return res.json({ status: "fail", message: error.toString() });
  }
};
export const ProductLitByKeyword = async (req, res) => {
  try {
    return res.json({ status: "success" });
  } catch (error) {
    return res.json({ status: "fail", message: error.toString() });
  }
};

export const ProducReviewListByID = async (req, res) => {
  try {
    return res.json({ status: "success" });
  } catch (error) {
    return res.json({ status: "fail", message: error.toString() });
  }
};

export const CreateProductReview = async (req, res) => {
  try {
    return res.json({ status: "success" });
  } catch (error) {
    return res.json({ status: "fail", message: error.toString() });
  }
};
